### ISSUE TITLE
Error in timeCrypt building

### ISSUE THREAD

**Issue by rezafotohi** [TimeCrypt/timecrypt#2]
Hello Dear Lukas

This is the Linux and compose version I installed:
_Ubuntu 16.04 LTS 32 bit_
and
_docker-compose version 1.8.0, build unknown_

The following error occurs when I run the first command (docker-compose up --build).

ERROR: 
_Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/_

I have two questions:
**Q1: **which Composer Docker file should I install?****
**Q2: **which docker-composer file should I install to work with the first command?****

**Comment by lubux** [comment]
The latest version should be installed:
Make sure that you have installed the latest docker-compose script 
(https://docs.docker.com/compose/install/)
